name: Static code checking
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/dep-setup

      - name: Run ESLint
        run: npx eslint . --max-warnings 0
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/dep-setup

      - name: Build
        run: bun run build
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: dummy
          CLERK_SECRET_KEY: dummy
